### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by krissaspdev** [2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore#12]
Hi. Is readme.md still valid?.
It does not work with EF7 rc-2-final...

I had to remove .AddSqlServer() and subclass OperationalContext

Kris

**Comment by ericgreenmix** [comment]
Thanks. I just updated the docs to be inline with rc2. I am unsure what you are referring to with subclassing the `OperationalContext` though. I don't believe you should have to do that. Only the `ScopeConfigurationContext` and `ClientConfigurationContext` should have to be subclassed as you have to pass in the type to them. Could you elaborate on the issue you were having?
