### ISSUE TITLE
Working Sample

### ISSUE THREAD

**Issue by WisdomCorp** [2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore#13]
It would be great if there is a working sample with a Asp.Net Core or Javascript (SPA) integrating this with IdentityServer 4. 

That way we can know how all pieces are working together :)

Thanks

**Comment by freerider7777** [comment]
Yep, example needed. Strange that there is no IProfileService implementation needed to connect plugin to IdentityServer...

**Comment by jarroda** [comment]
@freerider7777 `IProfileService` is the interface used to connect user persistence to IdentityServer. This is often handled with something like AspNetIdentity or MembershipReboot, which have their own means for persisting to a database.  That functionality is outside the scope of this project.  

This project was always meant to be a stopgap to allow my team and other people in the community to use IS4 with EFCore until the IdentityServer team released an official plugin.  Now that has happened, and they have a working sample, so I would recommend switching to their project.  https://github.com/IdentityServer/IdentityServer4.EntityFramework
