### ISSUE TITLE
System.InvalidOperationException Microsoft.EntityFrameworkCore.DbContextOptions

### ISSUE THREAD

**Issue by senzacionale** [2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore#19]
I have problem with EFCore

I did everything the same as normally for any other EFCore project but here I always get 

> System.InvalidOperationException
> Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[TwentyTwenty.IdentityServer4.EntityFrameworkCore.DbContexts.ClientConfigurationContext`1[System.Guid]]' while attempting to activate 'Host.Web.Configuration.ClientConfigurationContext'.

Problem is here with RegisterClientStore:

```
builder.ConfigureEntityFramework()
                .RegisterOperationalStores()
                .RegisterClientStore<Guid, ClientConfigurationContext>()
                .RegisterScopeStore<Guid, ScopeConfigurationContext>();
```

Any idea why or what can be wrong?

**Comment by ericgreenmix** [comment]
Check out the updates to the readme. I have also pushed an update 1.1.2 to Nuget. After that update, following the docs for configuration should work. There were some changes made a couple weeks ago that broke the workflow when subclassing the contexts.

**Comment by senzacionale** [comment]
Thank you for a reply. Can you give me push permission that I can fix howto?

regards,
Mitja

**Comment by ericgreenmix** [comment]
Please submit a Pull Request.

**Comment by senzacionale** [comment]
Ok I will next time. 

Please change also

```
public class OperationalContextEx : OperationalContext
{
    public OperationalContext(DbContextOptions<OperationalContextEx> options)
        : base(options)
    { }
}
```

to

```
public class OperationalContextEx : OperationalContext
{
    public OperationalContextEx (DbContextOptions<OperationalContextEx> options)
        : base(options)
    { }
}
```

**Comment by jarroda** [comment]
Corrected.
