### ISSUE TITLE
Question: Where to put the databases

### ISSUE THREAD

**Issue by TrabacchinLuigi** [2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore#2]
I'm trying to test this package, and I wonder if I'm doing right:
I've subclassed the Scope and ClientConfiguration contexts.
Those two and the Operational context needs migrations and a datase each, right ?
I figured out they can live in the same database, but there is no relationship between them, is that in purpose ?
How do you ensure two contexts don't have some tables colliding ?

Let's say I want to rename a scope ... I have to search for it's name around and rename tables ...

**Comment by jarroda** [comment]
We followed the example of the [original](https://github.com/IdentityServer/IdentityServer3.EntityFramework/tree/master/Source/Core.EntityFramework/DbContexts) IS3 EF provider and split clients, scopes and operational tables into separate Contexts.  This allows for using different databases, or even different persistence technologies for storing each of these.  

It certainly doesn't require using separate databases however, We are using a single database for all contexts. We specify the table names in the context configuration, so there is no danger of tables colliding.  

... unless you override the table name to something different.  Why would you want to do that?  I suppose if you did, you could put each context into a separate schema.
