### ISSUE TITLE
Error to implement IClientConfigurationContext<Guid>, IScopeConfigurationContext<Guid>, IOperationalContext

### ISSUE THREAD

**Issue by alexralfonsom** [2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore#24]
Hello, 

I am implementing version 1.2.0, released yesterday, I have a problem in implementing:
public class YourDataContext: IClientConfigurationContext <Guid>, IScopeConfigurationContext <Guid>, IOperationalContext.

The system informs me that "**Can not resolve symbol 'IClientConfigurationContext**'" then download the source code which i use in my project and so could be resolved if the reference **IClientConfigurationContext**.

Do not know if pending a new release because the file project.json version is "version": "1.3.0- *".

Thank you so much

**Comment by aligin** [comment]
Yep. It will be very cool if the package will be released soon.

**Comment by wickstargazer** [comment]
can there be any pre-release? i am awaiting usage ..thankz

**Comment by aligin** [comment]
@wickstargazer I pulled the repository (1.3.0), built it and pushed to my local Nuget as a temporary solution :)

**Comment by wickstargazer** [comment]
did the same but added it as the class library ... works that way as well for aspnetcore :) 

Found an error ... TwentyTwenty.IdentityServer4.EntityFrameworkCore.Stores.PersistedGrantService is not implemented.

**Comment by ericgreenmix** [comment]
Hey Guys. With IdentityServer releasing their own EF provider (https://github.com/IdentityServer/IdentityServer4.EntityFramework) we are no longer going to be supporting this library anymore. We highly recommend that you switch over to this new EF provider from Idsvr.

**Comment by aligin** [comment]
It's bad. We are using you library since deep beta. The migration of the entire DB model and data ... it's a pain.

**Comment by ericgreenmix** [comment]
We had to go through that same migration process. It is a pain, as there are a decent amount of changes to the schema in Idsvr's version. However, we had to weigh the cost of continued support for our own version, against the time for that migration. In the end moving to the Idsvr provided library made the most sense.

It would have been great, since we were the most widely used IS4 EF provider, if we could have worked to move this library into the Idsvr repo as the official provider, however no one ever reached out to us about that. We were actually quite surprised when we saw they rebuilt their own provider.

**Comment by jarroda** [comment]
I merged in a pull request that adds support to this library for IS4 RC2.  I will push this to nuget as version 1.3.  I have also added a link to the CI (Appveyor) nuget feed for anybody wanting pre-release packages.  

We can no longer support new development on this library during work hours, but I will be happy to pull in pull requests from anybody wanting to contribute.

**Comment by jarroda** [comment]
Version 1.3 is now available on nuget. Closing this issue.

**Comment by wickstargazer** [comment]
Hello guys, I migrated, since i am just starting the build-up. Thankz for the headsup. Will be happy to contrib if there is anything needed 👍

**Comment by aligin** [comment]
@jarroda Thanks man. Think we'll migrate to IS4-EF after release. So continue to use you library for now.
