### ISSUE TITLE
Why we have a customizable key ?

### ISSUE THREAD

**Issue by TrabacchinLuigi** [2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore#3]
What's the point of having a customizabe key let's say for clients when actually the only real key is their name ?

**Comment by jarroda** [comment]
We made the keys customization across all the tables simply to allow people to use whatever they preferred, or to match what they were already using in their app.  We are using GUIDs in our app, but many people will prefer an integer type.

Some entities, such as client, have columns that could be a natural key.  Natural vs surrogate keys are debatable, but I prefer using a consistent surrogate key across the database.  Particularly with Entity Framework, the primary key column on the table is immutable, which is likely OK for a natural key, may not be.

**Comment by TrabacchinLuigi** [comment]
That would make sense to me if everything was inside the same database and relational, but in this case the surrogate keys are not used in the others stores ... 
Sorry for being tedious :smile: 
I'm trying to understand if I'll use this project, contribute to it, or do my own implementations, i already got two branches one with no custom keys and one with a single dbcontext, and trying to understand what better suits my needs :)
