### ISSUE TITLE
ClientConfigurationCorsPolicyService InvalidOperationException

### ISSUE THREAD

**Issue by pariesz** [2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore#5]
I'm getting the following exception when using ClientCredentials Grant:

> System.InvalidOperationException: The binary operator Equal is not defined for the types 'System.Nullable`1[System.Guid]' and 'System.String'.

Its originating from here:

>  at TwentyTwenty.IdentityServer4.EntityFramework7.Services.ClientConfigurationCorsPolicyService`1.<IsOriginAllowedAsync>d__2.MoveNext()

I'm using the following builds:

> "IdentityServer4": "1.0.0-beta1",
> "TwentyTwenty.IdentityServer4.EntityFramework7": "0.9.6",
> "EntityFramework.Core": "7.0.0-rc1-final",

It looks like something to do with the `ClientId` column in the `Clients` table conflicting with the EF conventions.

**Comment by philmh-isams** [comment]
I am also getting this exception.. Any luck in figuring it out?

**Comment by ericgreenmix** [comment]
Could we get a sample project that has this issue? Locally our Client Credentials client is not producing this exception.

**Comment by philmh-isams** [comment]
Hmmm... sample project is not a quick piece, but the issue occurs on line 24 of ClientConfigurationCorsPolicyService.cs:
[https://github.com/2020IP/TwentyTwenty.IdentityServer4.EntityFramework7/blob/7a5fdad8dad1506f40c1e6c1d577256940d90d11/src/TwentyTwenty.IdentityServer4.EntityFramework7/Services/ClientConfigurationCorsPolicyService.cs#L24](url)

And it seems to be the `.SelectMany(x1 => x1.AllowedCorsOrigins)` section in particular.
There are records in this associated table, and I am using `Guid` as my `TKey`

I'll see if I can find more.. I think it may be to do with the fact the foreign key wishes to reference `Client` from `AllowedCorsOrigins`, but convention would expect the foreign key to be `ClientId` which is a `string` and not a `System.Guid`

**Comment by philmh-isams** [comment]
If I replace this method with:

```
        public async Task<bool> IsOriginAllowedAsync(string origin)
        {
            var clients = await context.Clients.Include(x => x.AllowedCorsOrigins).ToListAsync();
            var urls = clients.SelectMany(x1 => x1.AllowedCorsOrigins).Select(x => x.Origin);

            return urls.Select(x => x.GetOrigin()).Where(x => x != null).Distinct()
                .Contains(origin, StringComparer.OrdinalIgnoreCase);
        }
```

Then I no longer get the exception. I am confident this has something to do with the fact `Client` navigation property is trying to map `ClientId` on `ClientCorsOrigin<TKey>` to `ClientId` on `Client<TKey>`, but even specifying the principal key as `Id` did not work within the `OnModelCreating` event in `ClientConfigurationContext`.

I used `EnsureCreated` to create my database code-first and the references have been created correctly in the database, but it may be there is an error with EF7. I tried copying the code for `ClientConfigurationCorsPolicyService` under IdentityServer3 and that raised the same exception.

I am thinking this is more a EF7 bug than yours, as I would expect the code to not being using convention when a primary key has been specified on the `Clients` table ;o)

**Comment by pariesz** [comment]
I added the issue to EF7:
https://github.com/aspnet/EntityFramework/issues/4852

They report the issue fixed in latest the codebase.

**Comment by ericgreenmix** [comment]
@pariesz have you had a chance to test this on the EF Core rc2 update we released?

**Comment by philmh-isams** [comment]
@ericgreenmix We are upgrading to RC2 as we speak and using EF Core, so I will let you know if it is successful.

**Comment by philmh-isams** [comment]
@ericgreenmix and @pariesz
We have upgraded to RC2 and it all appears to work now

**Comment by ericgreenmix** [comment]
That is great. @pariesz can you confirm this as well so we can close the issue?

**Comment by pariesz** [comment]
finally finished upgrading to RC2, yes the problem has been fixed
