### ISSUE TITLE
Fork of TwentyTwenty

### ISSUE THREAD

**Issue by klanglie** [2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore#9]
Not really an issue. Just wanted to let you know that I forked this project to a new location. Contributions welcome. BlueConcord.IdentityServer.EntityFrameworkCore

**Comment by ericgreenmix** [comment]
Why duplicate when you can submit PR's to us? Also there is a complete port to IS4 beta 2 with RC2 in the feature/rc2-port branch. It will be merged to master and pushed to nuget on Monday.
